name: Terraform Child Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform_child:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Terraform Parent Workflow
        uses: ./.gihub/actions/actions.yml